"""empty message

Revision ID: 17b82e62334d
Revises: 9eae735c56ea
Create Date: 2022-12-19 19:13:54.946092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b82e62334d'
down_revision = '9eae735c56ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wx_tokens', sa.Column('appid', sa.String(length=1024), nullable=False, comment='APPID'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wx_tokens', 'appid')
    # ### end Alembic commands ###
