"""empty message

Revision ID: 336470cc0f94
Revises: 435090f84715
Create Date: 2023-03-05 16:26:29.650749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336470cc0f94'
down_revision = '435090f84715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editor_works',
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('update_cnt', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='更新次数'),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标记'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workName', sa.Text(), nullable=False, comment='作品名称'),
    sa.Column('editorType', sa.Enum('作者', '编辑'), nullable=False),
    sa.Column('editorId', sa.Integer(), nullable=False, comment='作者ID'),
    sa.Column('workDate', sa.Date(), nullable=False, comment='发布时间'),
    sa.Column('workFee', sa.DECIMAL(precision=10, scale=5), nullable=False, comment='该作者/编辑在该作品中的应付稿酬'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('update_cnt', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='更新次数'),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标记'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allow_startswith', sa.Text(), nullable=False, comment='直接放行无需鉴权的URL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editor_list',
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('update_cnt', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='更新次数'),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标记'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editor', sa.String(length=20), nullable=False, comment='作者姓名'),
    sa.Column('deptId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deptId'], ['enroll_depts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('editor_list')
    op.drop_table('routes')
    op.drop_table('editor_works')
    # ### end Alembic commands ###
