"""empty message

Revision ID: 3ab7bbd11dfd
Revises: dc8e741812c4
Create Date: 2023-03-11 17:00:25.111788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab7bbd11dfd'
down_revision = 'dc8e741812c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editor_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cardId', sa.Text(), nullable=True, comment='银行卡号'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editor_list', schema=None) as batch_op:
        batch_op.drop_column('cardId')

    # ### end Alembic commands ###
