"""empty message

Revision ID: 435090f84715
Revises: 17b82e62334d
Create Date: 2022-12-26 20:12:13.494115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435090f84715'
down_revision = '17b82e62334d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_avatars_image',
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('update_cnt', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='更新次数'),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标记'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=1024), nullable=False, comment='图片的URL'),
    sa.Column('selected', sa.String(length=32), server_default='unselected', nullable=False, comment='图片是否被选中, 取值为 selected 或 unselected'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wx_avatars_image')
    # ### end Alembic commands ###
