"""empty message

Revision ID: 9d4c83896927
Revises: 336470cc0f94
Create Date: 2023-03-05 16:38:46.058345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4c83896927'
down_revision = '336470cc0f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('note', sa.Text(), nullable=True, comment='备注'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'note')
    # ### end Alembic commands ###
