"""empty message

Revision ID: 9eae735c56ea
Revises: 
Create Date: 2022-12-04 12:08:10.075555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eae735c56ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_app_secret',
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('update_cnt', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='更新次数'),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标记'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appid', sa.String(length=1024), nullable=False, comment='微信平台的appid'),
    sa.Column('secret', sa.String(length=1024), nullable=False, comment='微信平台的appsecret'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wx_app_secret')
    # ### end Alembic commands ###
