"""empty message

Revision ID: dc8e741812c4
Revises: c35c6c9a24e4
Create Date: 2023-03-09 16:00:27.688787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8e741812c4'
down_revision = 'c35c6c9a24e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editor_work_fees',
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('update_cnt', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='更新次数'),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标记'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editorType', sa.Enum('作者', '编辑'), nullable=False),
    sa.Column('editorId', sa.Integer(), nullable=False, comment='作者ID'),
    sa.Column('workId', sa.Integer(), nullable=False, comment='稿件ID'),
    sa.Column('workFee', sa.DECIMAL(precision=10, scale=5), nullable=True, comment='该作者/编辑在该作品中的应付稿酬'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('editor_fees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editor_fees',
    sa.Column('create_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_cnt', sa.SMALLINT(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('editorType', sa.VARCHAR(length=2), nullable=False),
    sa.Column('editorId', sa.INTEGER(), nullable=False),
    sa.Column('workId', sa.INTEGER(), nullable=False),
    sa.Column('workFee', sa.DECIMAL(precision=10, scale=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('editor_work_fees')
    # ### end Alembic commands ###
